version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - /
      - /azblob
      - /cmd/s2-server
      - /gcs
      - /s2env
      - /s3
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
