version: 2

project_name: s2-server

before:
  hooks:
    - go mod tidy

builds:
  - id: s2-server
    main: ./cmd/s2-server
    binary: s2-server
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mojatter/s2/server.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

dockers_v2:
  - id: s2
    ids:
      - s2-server
    dockerfile: server/Dockerfile.goreleaser
    images:
      - "{{ .Env.DOCKERHUB_USER }}/s2-server"
    tags:
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
