FROM golang:1.24-alpine
WORKDIR /app
RUN --mount=target=. cd s3 && \
    GOWORK=off go test -tags integtest -c -o /usr/local/bin/s3-integ-test .
ENTRYPOINT ["s3-integ-test", "-test.v", "-test.run", "TestS3Integration"]
